version: '3.7'
services:
  next-js-learning-app:
    container_name: next-js-learning-app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      APP_ENV: local
      NODE_ENV: local
      HTTPS_METHOD: noredirect # support both http and https